"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import type { StageProps } from "@/app/components/StageRouter";
import { createAnonSupabase } from "@/lib/supabase";
import type { GroupProfile, TripRoom } from "@/lib/types";

/**
 * GroupProfileStage — shows the AI-generated combined travel profile and the
 * group's tension points before destinations are surfaced. This is the priming
 * for Demo Moment 1 ("Why this place?") — the group sees where they overlap
 * and where they clash, so the destination recommendations land in context.
 *
 * Behaviour:
 * - On mount, fetch the persisted profile via
 *   `GET /api/agents/group-profile?roomId=...`.
 *   - 200 → render the profile.
 *   - 404 → host sees a "Generate group profile" button that POSTs to the
 *           same route; non-hosts see a waiting message.
 * - When the agent POST returns `{ error, retryable }`, the error is shown
 *   inline with a Retry button only when `retryable` is true.
 * - Host-only "Advance stage" button at the bottom (enabled only when a
 *   profile exists) PATCHes the stage endpoint and broadcasts `stage-change`
 *   so every client re-renders.
 */
export default function GroupProfileStage({
  room,
  identity,
  members,
  onRoomUpdated,
}: StageProps) {
  const isHost = identity.userId === room.hostUserId;

  // ── Profile fetch ────────────────────────────────────────────────────────────
  const [profile, setProfile] = useState<GroupProfile | null>(null);
  const [profileLoading, setProfileLoading] = useState(true);
  const [profileLoadError, setProfileLoadError] = useState<string | null>(null);

  // `notFound` is a *normal* state (no profile yet) — distinct from a real
  // error. The host sees a generate button; everyone else sees a waiting note.
  const [notFound, setNotFound] = useState(false);

  const fetchProfile = useCallback(async (): Promise<void> => {
    setProfileLoading(true);
    setProfileLoadError(null);
    try {
      const res = await fetch(
        `/api/agents/group-profile?roomId=${encodeURIComponent(room.id)}`,
        { cache: "no-store" },
      );
      if (res.status === 404) {
        setProfile(null);
        setNotFound(true);
        return;
      }
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as
          | { error?: string }
          | null;
        throw new Error(body?.error ?? "Failed to load group profile");
      }
      const data = (await res.json()) as GroupProfile;
      setProfile(data);
      setNotFound(false);
    } catch (err) {
      setProfileLoadError(
        err instanceof Error ? err.message : "Failed to load group profile",
      );
    } finally {
      setProfileLoading(false);
    }
  }, [room.id]);

  const fetchProfileRef = useRef(fetchProfile);
  fetchProfileRef.current = fetchProfile;

  // Keep a ref of the current profile so the poll interval can read it
  // without retriggering the effect.
  const profileRef = useRef<GroupProfile | null>(null);
  profileRef.current = profile;

  // Initial fetch + light polling so non-host clients pick up the profile
  // shortly after the host generates it. (We intentionally don't bake a
  // dedicated realtime channel for this — polling every 3s is plenty.)
  useEffect(() => {
    void fetchProfileRef.current();
    const interval = setInterval(() => {
      // Only keep polling while no profile has been loaded yet; once we have
      // one, the data is stable until the next stage.
      if (!profileRef.current) {
        void fetchProfileRef.current();
      }
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  // ── Generate (host only, auto-triggered on mount) ───────────────────────────
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [generateRetryable, setGenerateRetryable] = useState(false);

  async function handleGenerate() {
    if (generating) return;
    setGenerating(true);
    setGenerateError(null);
    setGenerateRetryable(false);
    try {
      const res = await fetch("/api/agents/group-profile", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ roomId: room.id }),
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as
          | { error?: string; retryable?: boolean }
          | null;
        setGenerateRetryable(body?.retryable === true);
        throw new Error(body?.error ?? "Failed to generate group profile");
      }
      const data = (await res.json()) as GroupProfile;
      setProfile(data);
      setNotFound(false);
    } catch (err) {
      setGenerateError(
        err instanceof Error ? err.message : "Failed to generate group profile",
      );
    } finally {
      setGenerating(false);
    }
  }

  // Auto-generate when host enters the stage and no profile exists yet
  const autoGeneratedRef = useRef(false);
  useEffect(() => {
    if (!isHost) return;
    if (autoGeneratedRef.current) return;
    if (profile || generating) return;
    if (!notFound) return; // still loading — wait for fetchProfile to complete
    autoGeneratedRef.current = true;
    void handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isHost, notFound, profile, generating]);

  // ── Stage advance (host only) ────────────────────────────────────────────────
  const [advancing, setAdvancing] = useState(false);
  const [advanceError, setAdvanceError] = useState<string | null>(null);

  async function handleAdvance() {
    if (advancing) return;
    setAdvancing(true);
    setAdvanceError(null);
    try {
      const res = await fetch(`/api/rooms/${room.roomCode}/stage`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ requestingUserId: identity.userId }),
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as
          | { error?: string; message?: string }
          | null;
        throw new Error(body?.message ?? body?.error ?? "Failed to advance stage");
      }
      const updated = (await res.json()) as TripRoom;
      onRoomUpdated(updated);
      void broadcastStageChange(room.id);
    } catch (err) {
      setAdvanceError(
        err instanceof Error ? err.message : "Failed to advance stage",
      );
    } finally {
      setAdvancing(false);
    }
  }

  // ── Render ───────────────────────────────────────────────────────────────────
  return (
    <section className="mx-auto flex max-w-3xl flex-col gap-6">
      <div className="border-4 border-pt-text-primary border-opacity-20 bg-[var(--pt-bg-card)] p-6 shadow-pixel-card">
        <p className="text-sm font-bold uppercase tracking-wide text-pt-text-primary">
          Current stage
        </p>
        <h2 className="mt-1 text-2xl font-bold text-pt-text-primary">Group profile</h2>
        <p className="mt-2 text-pt-text-primary">
          Here&apos;s how the AI sees your group — overlapping window, common
          interests, and the friction points to keep in mind before we pick a
          destination.
        </p>
        <p className="mt-2 text-xs font-semibold text-pt-text-primary">
          {members.length} {members.length === 1 ? "member" : "members"} in this
          room.
        </p>
      </div>

      {profileLoading && !profile ? (
        <div className="border-4 border-pt-text-primary border-opacity-20 bg-[var(--pt-bg-card)] p-6 shadow-pixel-card">
          <p className="text-sm font-semibold text-pt-text-primary">Loading group profile…</p>
        </div>
      ) : profileLoadError ? (
        <div
          className="p-6 shadow-pixel-card"
          style={{ border: "4px solid #B91C1C", backgroundColor: "#1A0000" }}
        >
          <p className="text-sm font-semibold" style={{ color: "#FCA5A5" }}>{profileLoadError}</p>
          <button
            type="button"
            onClick={() => void fetchProfile()}
            className="mt-3 px-3 py-1 text-sm font-bold active:translate-x-[2px] active:translate-y-[2px]"
            style={{ border: "2px solid #B91C1C", backgroundColor: "#2A0000", color: "#FCA5A5", boxShadow: "3px 3px 0px #7F1D1D" }}
          >
            Try again
          </button>
        </div>
      ) : profile ? (
        <ProfileView profile={profile} />
      ) : notFound ? (
        <div className="border-4 border-pt-text-primary border-opacity-20 bg-[var(--pt-bg-card)] p-6 shadow-pixel-card">
          {isHost ? (
            <>
              <h3 className="text-lg font-bold text-pt-text-primary">
                {generating ? "Generating group profile…" : "Generate the group profile"}
              </h3>
              <p className="mt-1 text-sm text-pt-text-primary">
                {generating
                  ? "The AI is analysing your group's characters, dates, and vibes — this takes a few seconds."
                  : "The AI will summarise your group from everyone's personas, availability, and destination interests."}
              </p>
              {!generating && (
                <button
                  type="button"
                  onClick={() => void handleGenerate()}
                  disabled={generating}
                  className="mt-4 border-4 border-pt-text-primary border-opacity-20 bg-[#38BDF8] px-4 py-2 font-bold text-pt-text-primary shadow-pixel-card hover:bg-[#0ea5e9] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none disabled:cursor-not-allowed disabled:opacity-50"
                >
                  Generate group profile
                </button>
              )}
              {generateError && (
                <div className="mt-3 flex flex-col items-start gap-2">
                  <p className="text-sm font-semibold text-red-600">{generateError}</p>
                  {generateRetryable && (
                    <button
                      type="button"
                      onClick={() => void handleGenerate()}
                      disabled={generating}
                      className="px-3 py-1 text-sm font-bold active:translate-x-[2px] active:translate-y-[2px] disabled:cursor-not-allowed disabled:opacity-50"
                      style={{ border: "2px solid #B91C1C", backgroundColor: "#2A0000", color: "#FCA5A5", boxShadow: "3px 3px 0px #7F1D1D" }}
                    >
                      {generating ? "Retrying…" : "Retry"}
                    </button>
                  )}
                </div>
              )}
            </>
          ) : (
            <p className="text-sm font-semibold text-pt-text-primary">
              Waiting for the host to generate the group profile…
            </p>
          )}
        </div>
      ) : null}

      {isHost ? (
        <div className="flex flex-col items-start gap-2">
          <button
            type="button"
            onClick={() => void handleAdvance()}
            disabled={advancing || !profile}
            className="border-4 border-pt-text-primary border-opacity-20 bg-[#FB923C] px-4 py-2 font-bold text-pt-text-primary shadow-pixel-card hover:bg-[#f97316] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none disabled:cursor-not-allowed disabled:opacity-50"
          >
            {advancing ? "Advancing…" : "Advance stage"}
          </button>
          {!profile && (
            <p className="text-xs font-semibold text-pt-text-primary">
              Generate the group profile before advancing.
            </p>
          )}
          {advanceError && (
            <p className="text-sm font-semibold text-red-600">{advanceError}</p>
          )}
        </div>
      ) : (
        <p className="text-sm font-semibold text-pt-text-primary">
          Waiting for the host to advance to the next stage…
        </p>
      )}
    </section>
  );
}

// ─── Presentational pieces ────────────────────────────────────────────────────

function ProfileView({ profile }: { profile: GroupProfile }) {
  return (
    <>
      <div className="border-4 border-pt-text-primary border-opacity-20 bg-[var(--pt-bg-card)] p-6 shadow-pixel-card">
        <h3 className="mb-4 text-lg font-bold text-pt-text-primary">Combined profile</h3>
        <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <Field label="Budget range" value={profile.budgetRange} />
          <Field
            label="Dominant pace"
            value={
              <span className="capitalize">{profile.dominantPace}</span>
            }
          />
          <Field
            label="Travel window"
            value={
              profile.travelWindow ? (
                <>
                  <span className="font-mono font-bold">
                    {profile.travelWindow.startDate}
                  </span>{" "}
                  →{" "}
                  <span className="font-mono font-bold">
                    {profile.travelWindow.endDate}
                  </span>
                </>
              ) : (
                <span className="font-semibold text-pt-text-primary opacity-60">No common window yet</span>
              )
            }
          />
          <Field
            label="Dominant traits"
            value={
              profile.dominantPersonaTraits.length > 0 ? (
                <TagList tags={profile.dominantPersonaTraits} tone="neutral" />
              ) : (
                <span className="font-semibold text-pt-text-primary opacity-60">None identified</span>
              )
            }
          />
        </dl>

        <div className="mt-6">
          <p className="text-xs font-bold uppercase tracking-wide text-pt-text-primary">
            Common interests
          </p>
          <div className="mt-2">
            {profile.commonInterests.length > 0 ? (
              <TagList tags={profile.commonInterests} tone="info" />
            ) : (
              <p className="text-sm font-semibold text-pt-text-primary opacity-60">
                No shared interests surfaced.
              </p>
            )}
          </div>
        </div>
      </div>

      <div
        role="alert"
        style={{
          border: "4px solid #92400E",
          backgroundColor: "#1C0F00",
          padding: "1.5rem",
          boxShadow: "4px 4px 0 #92400E",
        }}
      >
        <div className="flex items-center gap-2">
          <span aria-hidden="true">🗺️</span>
          <h3
            style={{ fontSize: "1.125rem", fontWeight: 700, color: "#FDE68A" }}
          >
            Things to Balance
          </h3>
        </div>
        <p
          style={{
            marginTop: "0.25rem",
            fontSize: "0.875rem",
            fontWeight: 600,
            color: "#FCD34D",
          }}
        >
          Your party may need to compromise on these points.
        </p>
        {profile.tensionPoints.length > 0 ? (
          <ul
            style={{
              marginTop: "0.75rem",
              display: "flex",
              flexDirection: "column",
              gap: "0.25rem",
              paddingLeft: "1.25rem",
              listStyleType: "disc",
              fontSize: "0.875rem",
              color: "#FEF3C7",
              lineHeight: 1.6,
            }}
          >
            {profile.tensionPoints.map((point, i) => (
              <li key={`${point}-${i}`}>{point}</li>
            ))}
          </ul>
        ) : (
          <p
            style={{
              marginTop: "0.75rem",
              fontSize: "0.875rem",
              fontWeight: 600,
              color: "#A7F3D0",
            }}
          >
            ✅ None — this group is well aligned.
          </p>
        )}
      </div>
    </>
  );
}

function Field({
  label,
  value,
}: {
  label: string;
  value: React.ReactNode;
}) {
  return (
    <div>
      <dt className="text-xs font-bold uppercase tracking-wide text-pt-text-primary">
        {label}
      </dt>
      <dd className="mt-1 text-sm font-semibold text-pt-text-primary">{value}</dd>
    </div>
  );
}

function TagList({
  tags,
  tone,
}: {
  tags: string[];
  tone: "info" | "neutral";
}) {
  const toneClass =
    tone === "info"
      ? "bg-[#38BDF8] text-pt-text-primary border-2 border-pt-text-primary border-opacity-20"
      : "bg-[#4ADE80] text-pt-text-primary border-2 border-pt-text-primary border-opacity-20";
  return (
    <ul className="flex flex-wrap gap-1.5">
      {tags.map((tag, i) => (
        <li
          key={`${tag}-${i}`}
          className={`px-2.5 py-0.5 text-xs font-bold shadow-pixel-sm ${toneClass}`}
        >
          {tag}
        </li>
      ))}
    </ul>
  );
}

/**
 * Broadcast a `stage-change` event so every connected client re-fetches the
 * room. Mirrors the helper in LobbyStage / AvailabilityStage.
 */
async function broadcastStageChange(roomId: string): Promise<void> {
  const supabase = createAnonSupabase();
  const channel = supabase.channel(`room:${roomId}:stage`);
  await new Promise<void>((resolve) => {
    channel.subscribe((status) => {
      if (status === "SUBSCRIBED") resolve();
    });
  });
  await channel.send({ type: "broadcast", event: "stage-change", payload: {} });
  void supabase.removeChannel(channel);
}
